dev_addr: "127.0.0.1:8001"
site_name: RundizBones
docs_dir: ".wiki"
nav:
    - Getting started: getting-started.md
    - 'Module folder structure': 
        - 'Folder structure': 'module-folder-structure.md'
        - 'Module Installer': 'module-folder/module-installer.md'
plugins: []